import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import type { AtlasData } from './data';

const labels: Record<string, string> = { course: 'Corsi', module: 'Moduli', unit: 'Unità', lesson: 'Lezioni', skill: 'Skill', evidence: 'Evidenze', assessment: 'Assessment', source: 'Fonti' };
const relationLabels: Record<string, string> = { PREREQUISITE_OF: 'È prerequisito di', RECOMMENDED_BEFORE: 'È consigliato prima di', PART_OF: 'Fa parte di', TEACHES: 'Insegna', REINFORCES: 'Rinforza', ASSESSES: 'Valuta', EVIDENCE_FOR: 'È evidenza per', REQUIRED_BY: 'È richiesto da' };
export function GraphPage({ data }: { data: AtlasData }) {
  const [params, setParams] = useSearchParams(), [type, setType] = useState('all'), [query, setQuery] = useState('');
  const selected = data.graph.nodes.find(n => n.id === params.get('node'));
  const types = [...new Set(data.graph.nodes.map(n => n.type))].sort();
  const nodes = data.graph.nodes.filter(n => (type === 'all' || n.type === type) && `${n.id} ${n.title}`.toLowerCase().includes(query.toLowerCase().trim()));
  const assessmentModule = selected && data.modules.find(m => m.assessment_id === selected.id);
  const contentRoute = selected && (data.routes.find(r => r.id === selected.id)?.path ?? (assessmentModule ? `${assessmentModule.route}?view=assessment` : undefined));
  const skill = selected && data.skills.find(s => s.id === selected.id);
  return <div className="content-page graph-page"><header className="page-heading"><h1>Knowledge graph</h1><p>{data.graph.nodes.length} nodi e {data.graph.edges.length} relazioni. Esplora la struttura e le evidenze con un indice navigabile da tastiera.</p><Link className="text-link" to="/">Apri la mappa dei corsi</Link></header><div className="graph-filters"><label>Tipo di nodo<select value={type} onChange={e => setType(e.target.value)}><option value="all">Tutti i tipi</option>{types.map(t => <option key={t} value={t}>{labels[t] ?? t}</option>)}</select></label><label>Filtra i nodi<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="ID o titolo" /></label></div><div className="graph-index-layout"><section aria-label="Nodi del grafo"><p className="muted" role="status">{nodes.length} nodi trovati</p>{!nodes.length && <p className="empty-note">Nessun nodo corrisponde ai filtri. Prova un altro ID o scegli tutti i tipi.</p>}<ul className="node-list">{nodes.map(n => <li key={n.id}><button aria-pressed={selected?.id === n.id} onClick={() => setParams({ node: n.id }, { preventScrollReset: true })}><span className="mono">{n.id}</span><strong>{n.title}</strong><span className="muted">{labels[n.type] ?? n.type}</span></button></li>)}</ul></section><aside className="node-detail" aria-label="Dettaglio del nodo">{selected ? <><h2>{selected.title}</h2><p className="mono break-id">{selected.id}</p>{contentRoute && <Link className="text-link" to={contentRoute}>Apri il contenuto</Link>}{skill && <><dl className="semantic-notes"><div><dt>Coverage SSRI</dt><dd>{skill.ssri_coverage.level} · Copertura della fonte</dd></div><div><dt>Target IronMath</dt><dd>{skill.ironmath_requirement.level} · Requisito</dd></div><div><dt>Mastery personale</dt><dd>Non valutata</dd></div></dl><p>{skill.gap.note}</p><p className="muted">Confidence: {skill.gap.confidence}</p></>}<h3>Relazioni</h3><ul className="relation-list">{data.graph.edges.filter(e => e.from === selected.id || e.to === selected.id).map(e => { const outgoing = e.from === selected.id, other = outgoing ? e.to : e.from; return <li key={`${e.from}-${e.type}-${e.to}`}><span>{outgoing ? relationLabels[e.type] ?? e.type : `In ingresso · ${relationLabels[e.type] ?? e.type}`}</span><button onClick={() => setParams({ node: other }, { preventScrollReset: true })}>{other}</button></li>; })}</ul></> : <><h2>{params.get('node') ? 'Nodo non disponibile' : 'Scegli un nodo'}</h2><p className="muted">Il dettaglio mostra i collegamenti reali del grafo. Seleziona un nodo dall’indice.</p></>}</aside></div></div>;
}
