import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { AtlasData } from './data';
import type { ReadingState } from './useReading';
import { Icon } from './Icon';

export function ProgressPage({ data, reading }: { data: AtlasData; reading: ReadingState }) {
  const [confirm, setConfirm] = useState(false), count = reading.progress.read_lesson_ids.length;
  return <div className="content-page"><header className="page-heading"><h1>Il mio studio</h1><p>Ritrova le lezioni che hai segnato come lette. I segni restano in questo browser e non certificano competenza.</p></header><section className="reading-summary"><h2>{count} di {data.lessons.length} lezioni segnate come lette</h2><p className="muted">Mastery personale: non valutata. Nessun assessment personale registrato.</p></section>{reading.issue && <p className="storage-note" role="status">{reading.issue} I dati salvati incompatibili restano intatti fino all’azzeramento; puoi usare i segni in questa sessione.</p>}{!count && <p className="empty-note">Non hai ancora segnato una lezione. Aprine una dal percorso e usa «Segna come letta» quando vuoi ritrovarla qui.</p>}<ul className="reading-list">{data.lessons.map(l => <li key={l.id}><button className="reading-toggle" aria-label={`${reading.progress.read_lesson_ids.includes(l.id) ? 'Rimuovi il segno di lettura' : 'Segna come letta'}: ${l.title}`} aria-pressed={reading.progress.read_lesson_ids.includes(l.id)} onClick={() => reading.toggle(l.id)}><Icon name={reading.progress.read_lesson_ids.includes(l.id) ? 'check' : 'plus'} size={20} /></button><Link to={l.route}><span className="mono">{l.id}</span><h2>{l.title}</h2></Link><span className="content-status">draft</span></li>)}</ul><section className="plain-section"><h2>Dati di questo browser</h2><p>Puoi azzerare i segni di lettura. L’esportazione e l’importazione sono previste per una versione futura; al momento non sono disponibili.</p>{confirm ? <div className="inline-confirm"><p>Azzerare tutti i segni di lettura di questo browser?</p><button className="secondary-button" onClick={() => { reading.reset(); setConfirm(false); }}>Azzera i segni</button><button className="quiet-button" onClick={() => setConfirm(false)}>Annulla</button></div> : <button className="secondary-button" onClick={() => setConfirm(true)}>Azzera il progresso di lettura</button>}</section></div>;
}
