import { ROOT, loadModel, runCLI, coursePath, writeArtifacts } from './lib/repository.mjs';
const cell = value => String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const table = (headers, rows) => `| ${headers.join(' | ')} |\n| ${headers.map(() => '---').join(' | ')} |\n` + rows.map(r => `| ${r.map(cell).join(' | ')} |`).join('\n') + '\n';
export function renderReports(m) {
  const courses = [...m.courses].sort((a, b) => a.order - b.order);
  const skills = [...m.skills].sort((a, b) => a.id < b.id ? -1 : 1);
  const audit = m.repositories.repositories.map(r => `- ${r.repository}: audit \`${r.audited_commit}\` (${r.audited_tracked_files} file); locale \`${r.observed_local_commit}\` (${r.observed_tracked_files} file), drift \`${r.drift_status}\`. ${r.verification_note}`).join('\n');
  const header = (title, source) => `GENERATED — DO NOT EDIT DIRECTLY\nSource: ${source}\nRegenerate: npm run build:reports\n\n# ${title}\n\nCoverage della fonte ≠ mastery personale. C descrive il materiale SSRI; M è il requisito IronMath, non una competenza attribuita al learner. Stato del contenuto e assessment personale restano separati.\n\n${audit}\n\n`;
  const evidence = id => `\`${id}\``;
  const sourceTable = records => table(['Evidence ID', 'Path nello snapshot', 'Tipo', 'Claim', 'Confidence / provenienza'], records.map(e => [evidence(e.id), `\`${e.path}\``, e.evidence_type, e.claim, `${e.confidence} / ${e.provenance}`]));
  const cLink = id => { const c = courses.find(c => c.id === id); return `[${id}](../${coursePath(c)})`; };
  const skillsTable = (which) => table(['Skill', 'Titolo', which === 'ssri_coverage' ? 'Coverage' : 'Target', 'Evidence ID'], skills.map(s => [s.id, s.title, s[which].level, s[which].evidence_ids.map(evidence).join(', ')]));
  const required = m.graph.edges.filter(e => e.type === 'PREREQUISITE_OF');
  const dag = '```mermaid\ngraph TD\n' + courses.map(c => `  ${c.id.replace('-', '_')}["${c.id}"]`).join('\n') + '\n' + required.map(e => `  ${e.from.replace('-', '_')} --> ${e.to.replace('-', '_')}`).join('\n') + '\n```\n';
  return {
    'reports/ssri-coverage.md': header('Coverage SSRI', 'catalog/skills/*.json; sources/evidence/ssri-coverage.json; sources/repositories.json') + skillsTable('ssri_coverage') + '\n## Evidenze e limiti\n\n' + sourceTable(m.evidence.filter(e => e.repository_id === 'ssri')),
    'reports/ironmath-requirements.md': header('Requisiti IronMath', 'catalog/skills/*.json; sources/evidence/ironmath-requirements.json; sources/repositories.json') + skillsTable('ironmath_requirement') + '\n## Anchor e requisiti del prodotto\n\n' + sourceTable(m.evidence.filter(e => e.repository_id === 'ironmath')),
    'reports/gap-analysis.md': header('Gap analysis deduplicata', 'catalog/skills/*.json; sources/evidence/*.json; sources/repositories.json') + 'Non si sottraggono i livelli C e M: ogni riga spiega il ponte operativo, anche quando la base accademica è sostanziale. Un solo corso possiede ogni cluster.\n\n' + table(['Skill', 'C / target M', 'Priorità', 'Corso proprietario', 'Evidenze SSRI → IronMath', 'Confidence', 'Ponte operativo'], skills.map(s => [s.id, `${s.ssri_coverage.level} / ${s.ironmath_requirement.level}`, s.priority, cLink(s.primary_course_id), s.ssri_coverage.evidence_ids.map(evidence).join(', ') + ' → ' + s.ironmath_requirement.evidence_ids.map(evidence).join(', '), s.gap.confidence, s.gap.note])),
    'reports/roadmap-taxonomy-map.md': header('Mappa tassonomica roadmap.sh', 'sources/taxonomies/roadmap-sh.json; catalog/taxonomy-allowlist.json; catalog/skills/*.json; curriculum/courses/*/course.json; sources/repositories.json') + 'Sole label, URL candidate e relazioni. `taxonomy-label-only`. Reviewed_at è la data del baseline; pending indica assenza di verifica URL in questa esecuzione. Nessun contenuto roadmap incorporato.\n\n' + table(['Label / URL', 'Reviewed at', 'Verifica', 'Corsi', 'Skill'], m.taxonomy.records.map(t => [`[${t.label}](${t.url})`, t.reviewed_at, t.verification_status, courses.filter(c => c.roadmap_taxonomy.includes(t.label)).map(c => c.id).join(', ') || '—', skills.filter(s => s.roadmap_taxonomy.includes(t.label)).map(s => s.id).join(', ') || '—'])),
    'reports/curriculum-roadmap.md': header('Roadmap curricolare', 'curriculum/courses/*/course.json; curriculum/courses/*/modules/*/module.json; catalog/skills/*.json; graph/knowledge-graph.json; sources/repositories.json') + `Conteggi generati: ${courses.length} corsi; ${skills.length} skill; ${m.modules.length} starter module; ${m.graph.nodes.length} nodi; ${m.graph.edges.length} archi (${required.length} required).\n\n` + table(['Ordine', 'Corso', 'Titolo', 'Fase', 'Priorità', 'Target', 'Stato', 'Required', 'Recommended'], courses.map(c => [c.order, cLink(c.id), c.title, c.phase, c.priority, c.target_mastery, c.status, c.required_prerequisite_course_ids.join(', ') || '—', c.recommended_prerequisite_course_ids.join(', ') || '—'])) + '\n## DAG required\n\nSolo gli archi required sono mostrati; recommended non bloccano il percorso. EAT-016 è un ramo parallelo dopo EAT-001; EAT-012 non ha required nel blueprint, ma i recommended aiutano a prepararlo.\n\n' + dag + '\n## Moduli pianificati e attivi\n\n' + courses.map(c => `### ${c.id}\n\n${c.outcomes.join(' ')}\n\n` + table(['ID', 'Titolo', 'Outcome', 'Stato'], c.planned_modules.map(mod => [mod.id, mod.title, mod.outcome, mod.status]))).join('\n'),
  };
}
runCLI(import.meta, () => { writeArtifacts(ROOT, renderReports(loadModel())); });
